apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
        change-trigger: "v3"
    spec:
      containers:
        - name: python-app
          image: ragu89/python-app:latest
          ports:
            - containerPort: 80
